# Generated by Django 4.0.4 on 2022-06-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion_Antropometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_evaluacion', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('size', models.FloatField()),
                ('weight', models.FloatField()),
                ('bodyfat', models.FloatField()),
                ('musclemass', models.FloatField()),
                ('IMC', models.FloatField()),
            ],
            options={
                'verbose_name': 'Evaluacion Antropometrica',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('ingredients', models.CharField()),
                ('number_of_grams', models.FloatField()),
                ('amount_of_cholesterol', models.FloatField()),
                ('vitamins', models.CharField()),
                
            ],
            options={
                'verbose_name': 'Recetas',
                'verbose_name_plural': 'Recetas',
            },
        ),
    ]
