# Generated by Django 4.0.4 on 2022-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutricion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=40)),
                ('ingredients', models.CharField(max_length=200)),
                ('number_of_grams', models.FloatField()),
                ('amount_of_cholesterol', models.FloatField()),
                ('vitamins', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Recetas Saludables',
                'verbose_name_plural': 'Recetas',
            },
        ),
    ]
