# Generated by Django 4.0.4 on 2022-06-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutricion', '0003_clientes_image_recetas_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion_antropometrica',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clientes'),
        ),
    ]
