# Generated by Django 4.0.4 on 2022-06-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutricion', '0004_evaluacion_antropometrica_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion_antropometrica',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evaluacion_antropometrica'),
        ),
    ]
