# Generated by Django 4.0.4 on 2022-06-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutricion', '0005_alter_evaluacion_antropometrica_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion_antropometrica',
            name='image',
        ),
    ]
