# Generated by Django 4.0.4 on 2022-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutricion', '0006_remove_evaluacion_antropometrica_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion_antropometrica',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clientes'),
        ),
    ]
