# Generated by Django 4.0.4 on 2022-07-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutricion', '0009_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
