# Generated by Django 4.0.4 on 2022-07-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutricion', '0010_alter_avatar_last_name_alter_avatar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
